#!/bin/bash
# Set up Tailscale HTTPS certificates and generate Caddyfile
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Load config
if [[ ! -f "$SCRIPT_DIR/config.env" ]]; then
    echo -e "${RED}Error: config.env not found${NC}"
    echo "Run: cp config.env.example config.env"
    exit 1
fi
source "$SCRIPT_DIR/config.env"

# Defaults
CERT_DIR="${CERT_DIR:-$SCRIPT_DIR/certs}"
MCP_PORT="${MCP_PORT:-8080}"
WEB_PORT="${WEB_PORT:-8000}"
HTTPS_PORT="${HTTPS_PORT:-443}"

# Get Tailscale hostname
echo "Getting Tailscale hostname..."
TS_HOSTNAME=$(tailscale status --json 2>/dev/null | grep -o '"DNSName":"[^"]*"' | head -1 | cut -d'"' -f4 | sed 's/\.$//')

if [[ -z "$TS_HOSTNAME" ]]; then
    echo -e "${RED}Error: Could not determine Tailscale hostname${NC}"
    echo "Make sure Tailscale is connected: tailscale status"
    exit 1
fi

echo -e "${GREEN}Tailscale hostname: $TS_HOSTNAME${NC}"

# Create cert directory
mkdir -p "$CERT_DIR"

# Fetch certificates
echo
echo "Fetching certificates from Tailscale..."
echo "(This may require sudo for the first time)"

if tailscale cert --cert-file="$CERT_DIR/$TS_HOSTNAME.crt" --key-file="$CERT_DIR/$TS_HOSTNAME.key" "$TS_HOSTNAME"; then
    echo -e "${GREEN}Certificates saved to $CERT_DIR/${NC}"
else
    echo -e "${RED}Failed to fetch certificates${NC}"
    echo "Make sure HTTPS is enabled in your Tailscale admin console:"
    echo "  https://login.tailscale.com/admin/dns"
    exit 1
fi

# Generate Caddyfile
CADDYFILE="$SCRIPT_DIR/Caddyfile"
echo
echo "Generating Caddyfile..."

cat > "$CADDYFILE" << EOF
# Generated by setup-tailscale.sh
# Hostname: $TS_HOSTNAME

{
    # Use custom HTTPS port if not 443
    $(if [[ "$HTTPS_PORT" != "443" ]]; then echo "https_port $HTTPS_PORT"; fi)

    # Disable automatic HTTPS (we have our own certs)
    auto_https off
}

$TS_HOSTNAME$(if [[ "$HTTPS_PORT" != "443" ]]; then echo ":$HTTPS_PORT"; fi) {
    tls $CERT_DIR/$TS_HOSTNAME.crt $CERT_DIR/$TS_HOSTNAME.key

    # MCP server endpoint
    handle /mcp* {
        reverse_proxy localhost:$MCP_PORT
    }

    # Web UI (everything else)
    handle {
        reverse_proxy localhost:$WEB_PORT
    }

    # Logging
    log {
        output file $SCRIPT_DIR/logs/access.log {
            roll_size 10mb
            roll_keep 5
        }
    }
}
EOF

echo -e "${GREEN}Caddyfile generated: $CADDYFILE${NC}"

# Create logs directory
mkdir -p "$SCRIPT_DIR/logs"

# Summary
echo
echo "========================================"
echo -e "${GREEN}Setup complete!${NC}"
echo "========================================"
echo
echo "Your services will be available at:"
if [[ "$HTTPS_PORT" == "443" ]]; then
    echo "  MCP: https://$TS_HOSTNAME/mcp"
    echo "  Web: https://$TS_HOSTNAME/"
else
    echo "  MCP: https://$TS_HOSTNAME:$HTTPS_PORT/mcp"
    echo "  Web: https://$TS_HOSTNAME:$HTTPS_PORT/"
fi
echo
echo "MCP client configuration:"
echo '  {'
echo '    "mcpServers": {'
echo '      "notes": {'
if [[ "$HTTPS_PORT" == "443" ]]; then
    echo "        \"url\": \"https://$TS_HOSTNAME/mcp\","
else
    echo "        \"url\": \"https://$TS_HOSTNAME:$HTTPS_PORT/mcp\","
fi
echo '        "headers": {'
echo '          "Authorization": "Bearer YOUR_API_KEY"'
echo '        }'
echo '      }'
echo '    }'
echo '  }'
echo
echo "Next steps:"
echo "  1. Ensure you have API keys: uv run notes-admin auth list"
echo "  2. Start services: ./start.sh"
